### ISSUE TITLE
Provide a docker image for SonarQube community edition

### ISSUE THREAD

**Issue by janos-ss** [SonarSource/docker-sonarqube#213]
See also https://jira.sonarsource.com/browse/MMF-1449

### Sub-tasks

Required to create public PRs:

- [x] Define images with appropriate aliases (6.7.6-community, 6.7-community, lts, 7.4-community, latest)
  - https://github.com/docker-library/docs/pull/1367
  - https://github.com/docker-library/official-images/pull/5098
- [x] Create simple automated tests for the images (get inspired by [Elastic](https://github.com/elastic/elasticsearch-docker/tree/master/tests))
- [ ] ~~(optional) Create automated tests as [recommended in official images repo](https://github.com/docker-library/official-images/tree/master/test)~~
- [x] Make it possible to pass all `sonar.` parameters using Docker env variables
- [x] Document how to use parameters via Docker environment variables (also, adopting [Elastic](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-configuration-methods)'s approach to documentation)
- [x] Document how to use bind-mounted persistent volumes
- [x] Document how to create custom images containing your configuration and plugins

SonarQube public documentation:

- [x] Document how to use Docker in [Get started in 2 minutes](https://docs.sonarqube.org/display/SONAR/Get+Started+in+Two+Minutes)
- [x] Document how to use Docker in [Installing the server](https://docs.sonarqube.org/display/SONAR/Installing+the+Server)

SonarSource internal documentation, etc:

- [x] Document how to release a new version
- [x] Add to SonarQube release process a step to update Docker images
- [x] Add open PRs to Platform Team's wallboard widget
- [x] (optional) Do a triage of existing GitHub PRs
- [x] (optional) Do a triage of existing GitHub Issues
- [x] (optional) Notify current threads of the availability of the new images and docs

**Comment by janos-ss** [comment]
The new images were released. You can give them a spin with, for example:

```
docker pull sonarqube
docker run -p 9000:9000 sonarqube  # runs latest: 7.4
docker run -p 9000:9000 sonarqube:6.7.6-community
```
