### ISSUE TITLE
MMF-1777 Improve delivery workflow

### ISSUE THREAD

**Issue by pierre-guillot-sonarsource** [SonarSource/docker-sonarqube#291]
Subtasks of [MMF-1777](https://jira.sonarsource.com/browse/MMF-1777):

- [x] rework the folder structure to be able later to provide 7.9 and 8.x (and later DE and EE) (#296)
- [x] add Burgr hook to branches and PR (#294)
- [x] Improve delivery workflow, see what can be automated (#301)

Out of scope :
- investiguate a dogfood mechanism for the image running on docker (no k8 yet)
